name: CI/CD - Spring Boot Maven App

on:
  push:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # instantiate a new empty machine to run commands inside it
    - name: Checkout source code
      uses: actions/checkout@v4

    # setup the jdk 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # build maven skipping tests
    - name: build with maven
      run: mvn clean package -DskipTests

    # login to docker hub
    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # set image name variable
    - name: Set image name
      run: echo "IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/banka-digital-app" >> $GITHUB_ENV

    # build docker image
    - name: build docker image
      run: |
        docker build \
        -t $IMAGE:${{ github.sha }} \
        -t $IMAGE:latest \
        .

    # push docker image
    - name: push docker image
      run: |
        docker push $IMAGE:${{ github.sha }}
        docker push $IMAGE:latest

    # setup SSH
    - name: setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # deploy to VPS
    - name: deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVEUR_USER }}@${{ secrets.SERVER_IP }} >> 'EOF'
          set -e
          cd ${{ secrets.APP_PATH }}
          docker compose pull
          docker compose up -d
        EOF
