name: CI/CD - Spring Boot Maven App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # instantiate a new empty machine to run commands inside it
    - name: Checkout source code
      uses: actions/checkout@v4

    # setup the jdk 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # build maven skipping tests
    - name: build with maven
      run: mvn clean package -DskipTests

    # login to docker hub
    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # build docker image
    - name: build docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/banka-digital-app:${{ github.sha }} .

    # push docker image
    - name: push docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/banka-digital-app:${{ github.sha }}
